version: '3'
services:
  # MySQL
  MySql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    #restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql/:rw
      - ${MYSQL_CONFIG_FILENAME}:/etc/mysql/conf.d/mysql.cnf:ro
    networks:
      - default

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    environment:
      PMA_HOST: MySql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - MySql
    networks:
      - default
      
  cache:
    image: redis:6.2-alpine
    container_name: ${CACHE_CONTAINER_NAME}
    #restart: always
    ports:
      - ${CACHE_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ${CACHE_DATA_PATH}:/data
    networks:
      - default

  php:
    build: shared_services/php
    container_name: ${PHP_CONTAINER_NAME}
    volumes:
      - ${APPLICATION}:/var/www/html:rw
      - ${LOG_PATH}:/var/log:rw
      - ${PHP_INI_PATH}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_PATH}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./shared_data/php/ssh_config:/etc/ssh/ssh_config
    networks:
      - default

  nginx:
    build: shared_services/nginx
    container_name: ${NGINX_CONTAINER_NAME}
    links:
      - php
    depends_on:
      - php
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${APPLICATION}:/var/www/html:rw
      - ${LOG_PATH}:/var/log/nginx:rw
      - ${NGINX_VHOST_PATH}:/etc/nginx/conf.d/:ro
      - ${NGINX_CONFIG_FILENAME}:/etc/nginx/nginx.conf:ro
    networks:
      - default

networks:
  default:
      driver: bridge
      name: docker-network